sudo: required
services:
  - docker

before_install:
  - docker build -t aaysenur/docker-react-example -f Dockerfile.dev .

script:
  -   docker run -e CI=true aaysenur/docker-react-example npm run test

language: generic  

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-reacct"
  env: "DockerReacct-env"
  bucket_name: "elasticbeanstalk-us-east-2-550633764501"
  bucket_path: "docker-reacct"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY