sudo: required
services:
  - docker

before_install:
  - docker build -t aaysenur/docker-react-example -f Dockerfile.dev .

script:
  -   docker run aaysenur/docker-react-example npm run test -- --coverage

language: generic  