sudo: required
services:
  - docker

before_install:
  - docker build -t aaysenur/docker-react-example -f Dockerfile.dev .

script:
  -   docker run -e CI=true aaysenur/docker-react-example npm run test

language: generic  